### ISSUE TITLE
Request to include TURBBO on BSSO foundry

### ISSUE THREAD

**Issue by fatibaba** [bssofoundry/bssofoundry.github.io#1]
The TURBBO project aims to provide tools that will allow you to work with ontologies to define behaviours, input data on the relationship between behaviours, run analyses, and visualise the results to provide robust answers to questions about how behaviours are related. 

We currently have a set of ontologies available at https://github.com/fatibaba/turbbo that we wish to include in the BSSO foundry. 

TURBBO is structured as three separate components upper.owl, behaviours.owl, and behaviour_properties.owl. These have been combined to form the turbbo.owl. At the moment, adding the turbbo.owl to the BSSO foundry should be sufficient. 

PURL: https://purl.org/turbbo/turbbo.owl
Licence: [CC BY 4.0](http://creativecommons.org/licenses/by/4.0/)
Homepage: https://github.com/fatibaba/turbbo
Contact: [Fatima Maikore](mailto:f.maikore@sheffield.ac.uk)
Trackers: https://github.com/fatibaba/turbbo/issues
Domain: behavioural science

Thank you.

**Comment by jannahastings** [comment]
@fatibaba, thank you so much for your patience. We are working on this now! 

I noticed that two potential issues with getting TURBBO to work with the visualisation tool: 

1)  the main file `turbbo.owl` uses imports to include the content from separate development files. This is of course a standard OWL design pattern, however, the library that loads content for the visualisation tool requires (at the moment) that the content be pre-merged. You should be able to programmatically create a merged production release file from the separate development OWL files using the [ROBOT merge](http://robot.obolibrary.org/merge.html) function. _I actually just realised you do have a merged file in the repository. Can we make this the primary file?_

2) The IDs you are using are specific to each file, that is, you are using `https://purl.org/turbbo/bp`, `https://purl.org/turbbo/upper`. For the visualisation tool for technical reasons it would be better if there was a single pattern for the IDs and then just the numeric part varied e.g. TURBBO_xxxxxx. I realise this can potentially be more difficult to manage on the tool side across multiple edit files, but perhaps if each file gets a different numeric range within the overall numeric space? Alternatively, we will have to register several different namespaces for the single ontology. 

Please let me know what you think - thanks!

**Comment by fatibaba** [comment]
@jannahastings Thank you for working on this. 

It is alright to use our merged file as the primary file. 

Regarding the IDs for the files, we are actually restructuring the ontology at the moment. We want to make it one rather than three separate ontologies and so having the same base ID will make sense. The plan is to use https://purl.org/turbbo_xxx and I like your suggestion to use different numeric ranges to represent the different components of the ontology (we still want to maintain the idea of having separate components to enable independent reuse of those components). 

I'll need some time to change the IDs but I'll let you know when it is done. I can see you have already linked the ontology to the BSSO foundry site, thank you for that. 

Regards.

**Comment by fatibaba** [comment]
Hello @jannahastings,

We have made some updates to the ontology including changing the ID pattern, structure and name of the ontology. Instead of three ontologies, we now have one called RBBO (Relationships Between Behaviours Ontology). RBBO has three modules (formerly the three ontologies). 

The main ontology file is now the [RBBO.owl](https://github.com/fatibaba/turbbo/blob/main/RBBO.owl) (where I have merged all three modules) and the PURL is ```https://purl.org/turbbo/RBBO.owl```. Our new ID pattern is ```https://purl.org/turbbo/RBBO_xxxxxxx``` so I think it should be fine now for the visualisation tool. 

I guess the PURL and the name of the ontology also needs updating on bssofoundry.org. 

Thanks a lot :)

**Comment by b-gehrke** [comment]
Hallo @fatibaba,
thank you for updating. We were wondering why you choose to store the ontology in Turtle? The visualization tool expects one of the common OWL/XML or RDF/XML formats. Could you provide the ontology in one of these formats?

**Comment by b-gehrke** [comment]
Thank you for the supplied file. With that, RBBO ist now integrated in the visualization tool. Please take a look and let us know if you spot anything unexpected.

**Comment by fatibaba** [comment]
Hello @b-gehrke, 

RBBO is looking good in the visualisation tool. Thanks for adding it. 

I have a question, if I update our main ontology file so that it imports terms from different sources, will it cause any issues in the visualizer? Our ontology is structured such that we have three components and at the moment we have merged all three into one main OWL file but we want to change this. We want to use the OWL import feature instead to add the different ontology files into the main OWL file that is linked to the visualiser. This is just to make the maintenance easier for us but I worry it might break something in the visualization.
